Postinger/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Postinger.Data;
using Postinger.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Identity;


namespace Postinger.Controllers
{
    [ApiController]
    [Route("api/[controller]/[action]")]
    [AllowAnonymous]
    public class PostController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<PostController> _logger;
        private readonly UserManager<UserViewModel> _UserManager;

        public PostController(ApplicationDbContext context, ILogger<PostController> logger, UserManager<UserViewModel> userManager)
        {
            _context = context;
            _logger = logger;
            _UserManager = userManager;
        }

        /// <summary>
        /// Añade un nuevo Post.
        /// </summary>
        /// <param name = "postData" ></ param >
        [HttpPost]
        public void AddNewPost([FromBody] PostViewModel postData)
        {
            if (postData != null)
            {
                _context.Add(postData);
                _context.SaveChanges();
            }
        }

        ///// <summary>
        ///// Obtiene todos los posts por usuario
        ///// </summary>
        //[HttpGet]
        //public List<PostViewModel> GetAll() //TODO: Agregar AutoMapper
        //{
        //    //var userID = GetCurrentUserId();
        //    var userID = "4ed9f1f1-96c8-498e-b3dd-c8d57b4115c1";

        //    var posts = _context.Post
        //        //.Include(x => x.Comentarios)
        //        //    .ThenInclude(x => x.User)
        //        //.Include(x => x.Likes)
        //        .Where(x => x.UserId == userID);

        //    var test = posts.ToList();

        //    foreach (var item in test)
        //    {
        //        item.cantidadLike = _context.Like.Where(x => x.PostId == item.Id && x.Tipo == "like").Count();
        //        item.cantidadDislike = _context.Like.Where(x => x.PostId == item.Id && x.Tipo == "dislike").Count();
        //    }

        //    return test;
        //}

        /// <summary>
        /// Obtiene todos los posts
        /// </summary>
        [HttpGet]
        public List<PostViewModel> AllPosts()
        {
            //return _context.Post.GroupBy(x => x.UserId).ToList();
            var posts = _context.Post
                .Include(x => x.User)
                .ToList();

            foreach (var item in posts)
            {
                item.cantidadLike = _context.Like.Where(x => x.PostId == item.Id && x.Tipo == "like").Count();
                item.cantidadDislike = _context.Like.Where(x => x.PostId == item.Id && x.Tipo == "dislike").Count();
            }
            return posts;
        }

        /// <summary>
        /// Obtiene el id del usuario logueado
        /// </summary>
        [HttpGet]
        public string GetCurrentUserId()
        {
            var identity = (ClaimsIdentity)User.Identity;
            //var user = _UserManager.GetUserId();
            var user = _UserManager.GetUserAsync(HttpContext.User);



            IEnumerable<Claim> claims = identity.Claims;

            //var userLogged = _context.Users.Where(x => x.UserName == user.Result.UserName).FirstOrDefault();

            //var id = userLogged.Id;

            return "4ed9f1f1-96c8-498e-b3dd-c8d57b4115c1";
        }

        /// <summary>
        /// Añade un like a un post
        /// </summary>
        [HttpPost]
        public void AddLike([FromBody] LikesViewModel vm)
        {
            var likes = _context.Like;
            var validar = likes.Where(x => x.PostId == vm.PostId && x.UserId == vm.UserId).Count() > 0;
            if (validar == false)
            {
                var like = likes.Add(vm);
                _context.SaveChanges();
            }
        }
    }
}

Postinger/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Postinger.Data;
using Postinger.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Identity;


namespace Postinger.Controllers
{
    //[Route("api/[controller]")]
    //[ApiController]
    //[Authorize]
    [Authorize]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<UserController> _logger;
        private readonly UserManager<UserViewModel> _UserManager;
        //private readonly PostController _postController;

        public UserController(ApplicationDbContext context, ILogger<UserController> logger, UserManager<UserViewModel> userManager/*, PostController postController*/)
        {
            _context = context;
            _logger = logger;
            _UserManager = userManager;
            //_postController = postController;
        }

        public IActionResult User()
        {
            return View();
        }

        public string GetCurrentUserId() //TODO: Reemplazar por metodo de PostController por medio de Inyección
        {
            var user = _UserManager.GetUserAsync(HttpContext.User);

            var userLogged = _context.Users.Where(x => x.UserName == user.Result.UserName).FirstOrDefault();

            var id = userLogged.Id;

            return id;
        }

        public List<UserViewModel> GetAllUsers()
        {
            var userExclude = GetCurrentUserId();
            var users = _context.Users.Where(x => x.Id != userExclude).ToList();

            return users;
        }
    }
}

Postinger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Postinger</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link src="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <style>
        .fixed {
            position: fixed;
            width: 100%;
            z-index: 1;
        }
    </style>
    <header class="bodyContainer">
        <nav class="navbar fixed navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Postinger</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Post">My posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="User">Our users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Postinger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>